# Generated by Django 2.1.7 on 2019-05-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='api.TaskModel'),
        ),
    ]
