# Generated by Django 2.1.7 on 2019-05-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190514_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='api.TaskModel'),
        ),
    ]
