# Generated by Django 2.2.1 on 2019-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190525_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
